[package]
name = "dojo_autonomous_agents"
version = "0.1.0"
cairo-version = "1.1.0"


[cairo]
sierra-replace-ids = true

[dependencies]
dojo_core = { git = "https://github.com/dojoengine/dojo", version = "0.1.0"}
dojo_x = { path = ".."}
starknet = "1.0.0"

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0x0390595E0f30299328F610C689fcFf5B0ee48eE971f0742b5568e5Dd1DE6e324"

keystore_path = "../keystore.json"
keystore_password = "password"