[package]
name = "dojo_autonomous_agents"
version = "0.1.0"
cairo-version = "1.1.0"


[cairo]
sierra-replace-ids = true

[dependencies]
dojo_core = { git = "https://github.com/dojoengine/dojo", version = "0.1.0"}
starknet = "1.0.0"

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0x06f62894bfd81d2e396ce266b2ad0f21e0668d604e5bb1077337b6d570a54aea"
private_key = "0x07230b49615d175307d580c33d6fda61fc7b9aec91df0f5c1a5ebe3b8cbfee02"
world_address = "0x7f1d6c1b15e03673062d8356dc1174d5d85c310479ec49fe781e8bf89e4c4f8"

keystore_path = "../keystore.json"
keystore_password = "password"